create table todos (
  id number generated by default on null as identity constraint pk_todos primary key,
  description varchar2(255) not null,
  priority number (1) constraint c_todos_prio check (priority in (1,2,3)),
  done boolean default false not null
);